version: '3.8'
services:
  app:
    container_name: "backend"
    build: .
    ports:
      - "8080:8080"
    volumes:
      - "./src:/app"
      - "./static:/app/static"
      - "./templates:/app/templates"
    env_file: ".env"
